### PR TITLE
Fix build with rpm >= 4.15

### PR DESCRIPTION
**Pull request by pmatilai**
In rpm >= 4.15 VERIFY_SIGNATURE and VERIFY_DIGEST no longer exist
at all, instead all interfaces use the fine-grained vsflags disablers.

See also https://github.com/rpm-software-management/rpm/pull/747

Note that in rpm >= 4.14.2 rpm's signature checking could be used to enforce signature presence without jumping all those hoops locally, but this is just a minimal fix to get it to build and hopefully work on rpm >= 4.15, haven't really been able to test it however.

### CODE REVIEW

File: CMakeLists.txt [hunk 1]
```diff
@@ -105,13 +105,18 @@ IF ( ENABLE_USE_THREADS )
...
 
+INCLUDE(CheckSymbolExists)
 FIND_PACKAGE(Rpm REQUIRED)
 IF ( NOT RPM_FOUND)
   MESSAGE( FATAL_ERROR " rpm-devel not found" )
 ELSE ( NOT RPM_FOUND)
   INCLUDE_DIRECTORIES(${RPM_INCLUDE_DIR})
   # fix includes not relative to rpm
   INCLUDE_DIRECTORIES(${RPM_INCLUDE_DIR}/rpm)
+  CHECK_SYMBOL_EXISTS(VERIFY_DIGEST rpmcli.h VERIFYDIGEST_FOUND)
```
Comment (mlandres) [inline CMakeLists.txt]: Looks like the test does not work. It fails to find VERIFY_DIGEST in rpmvf.h (same with CHECK_CXX_SYMBOL_EXISTS). 

It compiles on the CI system because it has rpm-4.14.2 installed. On SLE systems with rpm-4.14.1 it fails (no ::rpmtsSetVfyFlags).

**Comment by Conan-Kudo** [comment]
@mlandres @bzeller @pmatilai Can this please be fixed up and merged? It's blocking my fixing of a FTBFS of zypp stack in Fedora 31.

**Comment by Conan-Kudo** [comment]
I've applied this patch against libzypp 17.14.0 to try to fix the build failure against rpm 4.15 in F31 and Rawhide, and I get the following test failure:

```
test 40
      Start 40: RpmPkgSigCheck_test

40: Test command: /builddir/build/BUILD/libzypp-17.14.0/x86_64-redhat-linux-gnu/tests/zypp/RpmPkgSigCheck_test "--catch_system_errors=no"
40: Test timeout computed to be: 10000000
40: Running 11 test cases...
40: /builddir/build/BUILD/libzypp-17.14.0/tests/zypp/RpmPkgSigCheck_test.cc(162): error: in "signed_pkg_nokey": check xpct == cs has failed [R: [4-Signatures public key is not available]
40:    [4-Signatures public key is not available] |     Header V3 RSA/SHA256 Signature, key ID 3dbdc284: NOKEY
40:    [0-Signature is OK] |     Header SHA1 digest: OK
40:    [0-Signature is OK] |     Header SHA256 digest: OK
40:    [0-Signature is OK] |     Payload SHA256 digest: OK
40:    [0-Signature is OK] |     MD5 digest: OK != R: [4-Signatures public key is not available]
40:    [4-Signatures public key is not available] |     Header V3 RSA/SHA256 Signature, key ID 3dbdc284: NOKEY
40:    [0-Signature is OK] |     Header SHA256 digest: OK
40:    [0-Signature is OK] |     Header SHA1 digest: OK
40:    [0-Signature is OK] |     Payload SHA256 digest: OK
40:    [4-Signatures public key is not available] |     V3 RSA/SHA256 Signature, key ID 3dbdc284: NOKEY
40:    [0-Signature is OK] |     MD5 digest: OK]
40: /builddir/build/BUILD/libzypp-17.14.0/tests/zypp/RpmPkgSigCheck_test.cc(179): error: in "signed_broken_pkg_nokey": check xpct == cs has failed [R: [2-Signature does not verify]
40:    [4-Signatures public key is not available] |     Header V3 RSA/SHA256 Signature, key ID 3dbdc284: NOKEY
40:    [0-Signature is OK] |     Header SHA1 digest: OK
40:    [0-Signature is OK] |     Header SHA256 digest: OK
40:    [2-Signature does not verify] |     Payload SHA256 digest: BAD (Expected 6632dfb6e78fd3346baa860da339acdedf6f019fb1b5448ba1baa6cef67de795 != 85156c232f4c76273bbbb134d8d869e93bbfc845dd0d79016856e5356dd33727)
40:    [2-Signature does not verify] |     MD5 digest: BAD (Expected 8e64684e4d5bd90c3c13f76ecbda9ee2 != 442a473472708c39f3ac2b5eb38b476f) != R: [2-Signature does not verify]
40:    [4-Signatures public key is not available] |     Header V3 RSA/SHA256 Signature, key ID 3dbdc284: NOKEY
40:    [0-Signature is OK] |     Header SHA256 digest: OK
40:    [0-Signature is OK] |     Header SHA1 digest: OK
40:    [2-Signature does not verify] |     Payload SHA256 digest: BAD (Expected 6632dfb6e78fd3346baa860da339acdedf6f019fb1b5448ba1baa6cef67de795 != 85156c232f4c76273bbbb134d8d869e93bbfc845dd0d79016856e5356dd33727)
40:    [2-Signature does not verify] |     V3 RSA/SHA256 Signature, key ID 3dbdc284: BAD
40:    [2-Signature does not verify] |     MD5 digest: BAD (Expected 8e64684e4d5bd90c3c13f76ecbda9ee2 != 442a473472708c39f3ac2b5eb38b476f)]
40: /builddir/build/BUILD/libzypp-17.14.0/tests/zypp/RpmPkgSigCheck_test.cc(197): error: in "signed_broken_header_pkg_nokey": check xpct == cs has failed [R: [2-Signature does not verify]
40:    [2-Signature does not verify] |     Header V3 RSA/SHA256 Signature, key ID 3dbdc284: BAD
40:    [2-Signature does not verify] |     Header SHA1 digest: BAD (Expected 9ca2e3aec038e562d33442271ee52c08ded0d637 != 95286fd653f927df0a42746e310861d3f89bb75c)
40:    [2-Signature does not verify] |     Header SHA256 digest: BAD (Expected e88100656c8e06b6e4bb9155f0dd111ef8042866941f02b623cb46e12a82f732 != 76b343bcb9b8aaf9998fdcf7392e234944a0b078c67667fa0d658208b9a66983)
40:    [2-Signature does not verify] |     Payload SHA256 digest: BAD (Expected 6632dfb6e78fd3346baa860da339acdedf6f019fb1b5448ba1baa6cef67de795 != 85156c232f4c76273bbbb134d8d869e93bbfc845dd0d79016856e5356dd33727)
40:    [2-Signature does not verify] |     MD5 digest: BAD (Expected 8e64684e4d5bd90c3c13f76ecbda9ee2 != 81df819a7d94638ff3ffe0bb93a7d177) != R: [2-Signature does not verify]
40:    [2-Signature does not verify] |     Header V3 RSA/SHA256 Signature, key ID 3dbdc284: BAD
40:    [2-Signature does not verify] |     Header SHA256 digest: BAD (Expected e88100656c8e06b6e4bb9155f0dd111ef8042866941f02b623cb46e12a82f732 != 76b343bcb9b8aaf9998fdcf7392e234944a0b078c67667fa0d658208b9a66983)
40:    [2-Signature does not verify] |     Header SHA1 digest: BAD (Expected 9ca2e3aec038e562d33442271ee52c08ded0d637 != 95286fd653f927df0a42746e310861d3f89bb75c)
40:    [2-Signature does not verify] |     Payload SHA256 digest: BAD (Expected 6632dfb6e78fd3346baa860da339acdedf6f019fb1b5448ba1baa6cef67de795 != 85156c232f4c76273bbbb134d8d869e93bbfc845dd0d79016856e5356dd33727)
40:    [2-Signature does not verify] |     V3 RSA/SHA256 Signature, key ID 3dbdc284: BAD
40:    [2-Signature does not verify] |     MD5 digest: BAD (Expected 8e64684e4d5bd90c3c13f76ecbda9ee2 != 81df819a7d94638ff3ffe0bb93a7d177)]
40: /builddir/build/BUILD/libzypp-17.14.0/tests/zypp/RpmPkgSigCheck_test.cc(225): error: in "signed_pkg_withkey": check xpct == cs has failed [R: [0-Signature is OK]
40:    [0-Signature is OK] |     Header V3 RSA/SHA256 Signature, key ID 3dbdc284: OK
40:    [0-Signature is OK] |     Header SHA1 digest: OK
40:    [0-Signature is OK] |     Header SHA256 digest: OK
40:    [0-Signature is OK] |     Payload SHA256 digest: OK
40:    [0-Signature is OK] |     MD5 digest: OK != R: [0-Signature is OK]
40:    [0-Signature is OK] |     Header V3 RSA/SHA256 Signature, key ID 3dbdc284: OK
40:    [0-Signature is OK] |     Header SHA256 digest: OK
40:    [0-Signature is OK] |     Header SHA1 digest: OK
40:    [0-Signature is OK] |     Payload SHA256 digest: OK
40:    [0-Signature is OK] |     V3 RSA/SHA256 Signature, key ID 3dbdc284: OK
40:    [0-Signature is OK] |     MD5 digest: OK]
40: /builddir/build/BUILD/libzypp-17.14.0/tests/zypp/RpmPkgSigCheck_test.cc(242): error: in "signed_broken_pkg_withkey": check xpct == cs has failed [R: [2-Signature does not verify]
40:    [0-Signature is OK] |     Header V3 RSA/SHA256 Signature, key ID 3dbdc284: OK
40:    [0-Signature is OK] |     Header SHA1 digest: OK
40:    [0-Signature is OK] |     Header SHA256 digest: OK
40:    [2-Signature does not verify] |     Payload SHA256 digest: BAD (Expected 6632dfb6e78fd3346baa860da339acdedf6f019fb1b5448ba1baa6cef67de795 != 85156c232f4c76273bbbb134d8d869e93bbfc845dd0d79016856e5356dd33727)
40:    [2-Signature does not verify] |     MD5 digest: BAD (Expected 8e64684e4d5bd90c3c13f76ecbda9ee2 != 442a473472708c39f3ac2b5eb38b476f) != R: [2-Signature does not verify]
40:    [0-Signature is OK] |     Header V3 RSA/SHA256 Signature, key ID 3dbdc284: OK
40:    [0-Signature is OK] |     Header SHA256 digest: OK
40:    [0-Signature is OK] |     Header SHA1 digest: OK
40:    [2-Signature does not verify] |     Payload SHA256 digest: BAD (Expected 6632dfb6e78fd3346baa860da339acdedf6f019fb1b5448ba1baa6cef67de795 != 85156c232f4c76273bbbb134d8d869e93bbfc845dd0d79016856e5356dd33727)
40:    [2-Signature does not verify] |     V3 RSA/SHA256 Signature, key ID 3dbdc284: BAD
40:    [2-Signature does not verify] |     MD5 digest: BAD (Expected 8e64684e4d5bd90c3c13f76ecbda9ee2 != 442a473472708c39f3ac2b5eb38b476f)]
40: /builddir/build/BUILD/libzypp-17.14.0/tests/zypp/RpmPkgSigCheck_test.cc(259): error: in "signed_broken_header_pkg_withkey": check xpct == cs has failed [R: [2-Signature does not verify]
40:    [2-Signature does not verify] |     Header V3 RSA/SHA256 Signature, key ID 3dbdc284: BAD
40:    [2-Signature does not verify] |     Header SHA1 digest: BAD (Expected 9ca2e3aec038e562d33442271ee52c08ded0d637 != 95286fd653f927df0a42746e310861d3f89bb75c)
40:    [2-Signature does not verify] |     Header SHA256 digest: BAD (Expected e88100656c8e06b6e4bb9155f0dd111ef8042866941f02b623cb46e12a82f732 != 76b343bcb9b8aaf9998fdcf7392e234944a0b078c67667fa0d658208b9a66983)
40:    [2-Signature does not verify] |     Payload SHA256 digest: BAD (Expected 6632dfb6e78fd3346baa860da339acdedf6f019fb1b5448ba1baa6cef67de795 != 85156c232f4c76273bbbb134d8d869e93bbfc845dd0d79016856e5356dd33727)
40:    [2-Signature does not verify] |     MD5 digest: BAD (Expected 8e64684e4d5bd90c3c13f76ecbda9ee2 != 81df819a7d94638ff3ffe0bb93a7d177) != R: [2-Signature does not verify]
40:    [2-Signature does not verify] |     Header V3 RSA/SHA256 Signature, key ID 3dbdc284: BAD
40:    [2-Signature does not verify] |     Header SHA256 digest: BAD (Expected e88100656c8e06b6e4bb9155f0dd111ef8042866941f02b623cb46e12a82f732 != 76b343bcb9b8aaf9998fdcf7392e234944a0b078c67667fa0d658208b9a66983)
40:    [2-Signature does not verify] |     Header SHA1 digest: BAD (Expected 9ca2e3aec038e562d33442271ee52c08ded0d637 != 95286fd653f927df0a42746e310861d3f89bb75c)
40:    [2-Signature does not verify] |     Payload SHA256 digest: BAD (Expected 6632dfb6e78fd3346baa860da339acdedf6f019fb1b5448ba1baa6cef67de795 != 85156c232f4c76273bbbb134d8d869e93bbfc845dd0d79016856e5356dd33727)
40:    [2-Signature does not verify] |     V3 RSA/SHA256 Signature, key ID 3dbdc284: BAD
40:    [2-Signature does not verify] |     MD5 digest: BAD (Expected 8e64684e4d5bd90c3c13f76ecbda9ee2 != 81df819a7d94638ff3ffe0bb93a7d177)]
40:
40: *** 6 failures are detected in the test module "Master Test Suite"
40:
40/80 Test #40: RpmPkgSigCheck_test ..............***Failed    0.18 sec
Running 11 test cases...
/builddir/build/BUILD/libzypp-17.14.0/tests/zypp/RpmPkgSigCheck_test.cc(162): error: in "signed_pkg_nokey": check xpct == cs has failed [R: [4-Signatures public key is not available]
   [4-Signatures public key is not available] |     Header V3 RSA/SHA256 Signature, key ID 3dbdc284: NOKEY
   [0-Signature is OK] |     Header SHA1 digest: OK
   [0-Signature is OK] |     Header SHA256 digest: OK
   [0-Signature is OK] |     Payload SHA256 digest: OK
   [0-Signature is OK] |     MD5 digest: OK != R: [4-Signatures public key is not available]
   [4-Signatures public key is not available] |     Header V3 RSA/SHA256 Signature, key ID 3dbdc284: NOKEY
   [0-Signature is OK] |     Header SHA256 digest: OK
   [0-Signature is OK] |     Header SHA1 digest: OK
   [0-Signature is OK] |     Payload SHA256 digest: OK
   [4-Signatures public key is not available] |     V3 RSA/SHA256 Signature, key ID 3dbdc284: NOKEY
   [0-Signature is OK] |     MD5 digest: OK]
/builddir/build/BUILD/libzypp-17.14.0/tests/zypp/RpmPkgSigCheck_test.cc(179): error: in "signed_broken_pkg_nokey": check xpct == cs has failed [R: [2-Signature does not verify]
   [4-Signatures public key is not available] |     Header V3 RSA/SHA256 Signature, key ID 3dbdc284: NOKEY
   [0-Signature is OK] |     Header SHA1 digest: OK
   [0-Signature is OK] |     Header SHA256 digest: OK
   [2-Signature does not verify] |     Payload SHA256 digest: BAD (Expected 6632dfb6e78fd3346baa860da339acdedf6f019fb1b5448ba1baa6cef67de795 != 85156c232f4c76273bbbb134d8d869e93bbfc845dd0d79016856e5356dd33727)
   [2-Signature does not verify] |     MD5 digest: BAD (Expected 8e64684e4d5bd90c3c13f76ecbda9ee2 != 442a473472708c39f3ac2b5eb38b476f) != R: [2-Signature does not verify]
   [4-Signatures public key is not available] |     Header V3 RSA/SHA256 Signature, key ID 3dbdc284: NOKEY
   [0-Signature is OK] |     Header SHA256 digest: OK
   [0-Signature is OK] |     Header SHA1 digest: OK
   [2-Signature does not verify] |     Payload SHA256 digest: BAD (Expected 6632dfb6e78fd3346baa860da339acdedf6f019fb1b5448ba1baa6cef67de795 != 85156c232f4c76273bbbb134d8d869e93bbfc845dd0d79016856e5356dd33727)
   [2-Signature does not verify] |     V3 RSA/SHA256 Signature, key ID 3dbdc284: BAD
   [2-Signature does not verify] |     MD5 digest: BAD (Expected 8e64684e4d5bd90c3c13f76ecbda9ee2 != 442a473472708c39f3ac2b5eb38b476f)]
/builddir/build/BUILD/libzypp-17.14.0/tests/zypp/RpmPkgSigCheck_test.cc(197): error: in "signed_broken_header_pkg_nokey": check xpct == cs has failed [R: [2-Signature does not verify]
   [2-Signature does not verify] |     Header V3 RSA/SHA256 Signature, key ID 3dbdc284: BAD
   [2-Signature does not verify] |     Header SHA1 digest: BAD (Expected 9ca2e3aec038e562d33442271ee52c08ded0d637 != 95286fd653f927df0a42746e310861d3f89bb75c)
   [2-Signature does not verify] |     Header SHA256 digest: BAD (Expected e88100656c8e06b6e4bb9155f0dd111ef8042866941f02b623cb46e12a82f732 != 76b343bcb9b8aaf9998fdcf7392e234944a0b078c67667fa0d658208b9a66983)
   [2-Signature does not verify] |     Payload SHA256 digest: BAD (Expected 6632dfb6e78fd3346baa860da339acdedf6f019fb1b5448ba1baa6cef67de795 != 85156c232f4c76273bbbb134d8d869e93bbfc845dd0d79016856e5356dd33727)
   [2-Signature does not verify] |     MD5 digest: BAD (Expected 8e64684e4d5bd90c3c13f76ecbda9ee2 != 81df819a7d94638ff3ffe0bb93a7d177) != R: [2-Signature does not verify]
   [2-Signature does not verify] |     Header V3 RSA/SHA256 Signature, key ID 3dbdc284: BAD
   [2-Signature does not verify] |     Header SHA256 digest: BAD (Expected e88100656c8e06b6e4bb9155f0dd111ef8042866941f02b623cb46e12a82f732 != 76b343bcb9b8aaf9998fdcf7392e234944a0b078c67667fa0d658208b9a66983)
   [2-Signature does not verify] |     Header SHA1 digest: BAD (Expected 9ca2e3aec038e562d33442271ee52c08ded0d637 != 95286fd653f927df0a42746e310861d3f89bb75c)
   [2-Signature does not verify] |     Payload SHA256 digest: BAD (Expected 6632dfb6e78fd3346baa860da339acdedf6f019fb1b5448ba1baa6cef67de795 != 85156c232f4c76273bbbb134d8d869e93bbfc845dd0d79016856e5356dd33727)
   [2-Signature does not verify] |     V3 RSA/SHA256 Signature, key ID 3dbdc284: BAD
   [2-Signature does not verify] |     MD5 digest: BAD (Expected 8e64684e4d5bd90c3c13f76ecbda9ee2 != 81df819a7d94638ff3ffe0bb93a7d177)]
/builddir/build/BUILD/libzypp-17.14.0/tests/zypp/RpmPkgSigCheck_test.cc(225): error: in "signed_pkg_withkey": check xpct == cs has failed [R: [0-Signature is OK]
   [0-Signature is OK] |     Header V3 RSA/SHA256 Signature, key ID 3dbdc284: OK
   [0-Signature is OK] |     Header SHA1 digest: OK
   [0-Signature is OK] |     Header SHA256 digest: OK
   [0-Signature is OK] |     Payload SHA256 digest: OK
   [0-Signature is OK] |     MD5 digest: OK != R: [0-Signature is OK]
   [0-Signature is OK] |     Header V3 RSA/SHA256 Signature, key ID 3dbdc284: OK
   [0-Signature is OK] |     Header SHA256 digest: OK
   [0-Signature is OK] |     Header SHA1 digest: OK
   [0-Signature is OK] |     Payload SHA256 digest: OK
   [0-Signature is OK] |     V3 RSA/SHA256 Signature, key ID 3dbdc284: OK
   [0-Signature is OK] |     MD5 digest: OK]
/builddir/build/BUILD/libzypp-17.14.0/tests/zypp/RpmPkgSigCheck_test.cc(242): error: in "signed_broken_pkg_withkey": check xpct == cs has failed [R: [2-Signature does not verify]
   [0-Signature is OK] |     Header V3 RSA/SHA256 Signature, key ID 3dbdc284: OK
   [0-Signature is OK] |     Header SHA1 digest: OK
   [0-Signature is OK] |     Header SHA256 digest: OK
   [2-Signature does not verify] |     Payload SHA256 digest: BAD (Expected 6632dfb6e78fd3346baa860da339acdedf6f019fb1b5448ba1baa6cef67de795 != 85156c232f4c76273bbbb134d8d869e93bbfc845dd0d79016856e5356dd33727)
   [2-Signature does not verify] |     MD5 digest: BAD (Expected 8e64684e4d5bd90c3c13f76ecbda9ee2 != 442a473472708c39f3ac2b5eb38b476f) != R: [2-Signature does not verify]
   [0-Signature is OK] |     Header V3 RSA/SHA256 Signature, key ID 3dbdc284: OK
   [0-Signature is OK] |     Header SHA256 digest: OK
   [0-Signature is OK] |     Header SHA1 digest: OK
   [2-Signature does not verify] |     Payload SHA256 digest: BAD (Expected 6632dfb6e78fd3346baa860da339acdedf6f019fb1b5448ba1baa6cef67de795 != 85156c232f4c76273bbbb134d8d869e93bbfc845dd0d79016856e5356dd33727)
   [2-Signature does not verify] |     V3 RSA/SHA256 Signature, key ID 3dbdc284: BAD
   [2-Signature does not verify] |     MD5 digest: BAD (Expected 8e64684e4d5bd90c3c13f76ecbda9ee2 != 442a473472708c39f3ac2b5eb38b476f)]
/builddir/build/BUILD/libzypp-17.14.0/tests/zypp/RpmPkgSigCheck_test.cc(259): error: in "signed_broken_header_pkg_withkey": check xpct == cs has failed [R: [2-Signature does not verify]
   [2-Signature does not verify] |     Header V3 RSA/SHA256 Signature, key ID 3dbdc284: BAD
   [2-Signature does not verify] |     Header SHA1 digest: BAD (Expected 9ca2e3aec038e562d33442271ee52c08ded0d637 != 95286fd653f927df0a42746e310861d3f89bb75c)
   [2-Signature does not verify] |     Header SHA256 digest: BAD (Expected e88100656c8e06b6e4bb9155f0dd111ef8042866941f02b623cb46e12a82f732 != 76b343bcb9b8aaf9998fdcf7392e234944a0b078c67667fa0d658208b9a66983)
   [2-Signature does not verify] |     Payload SHA256 digest: BAD (Expected 6632dfb6e78fd3346baa860da339acdedf6f019fb1b5448ba1baa6cef67de795 != 85156c232f4c76273bbbb134d8d869e93bbfc845dd0d79016856e5356dd33727)
   [2-Signature does not verify] |     MD5 digest: BAD (Expected 8e64684e4d5bd90c3c13f76ecbda9ee2 != 81df819a7d94638ff3ffe0bb93a7d177) != R: [2-Signature does not verify]
   [2-Signature does not verify] |     Header V3 RSA/SHA256 Signature, key ID 3dbdc284: BAD
   [2-Signature does not verify] |     Header SHA256 digest: BAD (Expected e88100656c8e06b6e4bb9155f0dd111ef8042866941f02b623cb46e12a82f732 != 76b343bcb9b8aaf9998fdcf7392e234944a0b078c67667fa0d658208b9a66983)
   [2-Signature does not verify] |     Header SHA1 digest: BAD (Expected 9ca2e3aec038e562d33442271ee52c08ded0d637 != 95286fd653f927df0a42746e310861d3f89bb75c)
   [2-Signature does not verify] |     Payload SHA256 digest: BAD (Expected 6632dfb6e78fd3346baa860da339acdedf6f019fb1b5448ba1baa6cef67de795 != 85156c232f4c76273bbbb134d8d869e93bbfc845dd0d79016856e5356dd33727)
   [2-Signature does not verify] |     V3 RSA/SHA256 Signature, key ID 3dbdc284: BAD
   [2-Signature does not verify] |     MD5 digest: BAD (Expected 8e64684e4d5bd90c3c13f76ecbda9ee2 != 81df819a7d94638ff3ffe0bb93a7d177)]

*** 6 failures are detected in the test module "Master Test Suite"
```

**Comment by Conan-Kudo** [comment]
Downstream RH bug: https://bugzilla.redhat.com/show_bug.cgi?id=1736067

**Comment by mlandres** [comment]
I'll have a look at it.
