### ISSUE TITLE
libzypp fails to build using cmake 3.28.0

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/libzypp#500]
From cmake 3.2.0's changelog:

```
+  * The "exec_program()" command, which has been deprecated since
+    CMake 3.0, has been removed by policy "CMP0153". Use the
+    "execute_process()" command instead.
```

cmake/modules/FindGpgme.cmake is making use of exec_program, which in turn makes build fail in some very 'fun' ways:

```
[   93s] 
[   93s]   /home/abuild/rpmbuild/BUILD/glibc-2.38/csu/../sysdeps/x86_64/start.S:103:(.text+0x2b):
[   93s]   undefined reference to `main'
[   93s] 
[   93s]   collect2: error: ld returned 1 exit status
[   93s] 
[   93s]   /bin/sh: line 1: -DOPENSSL_LOAD_CONF: command not found
[   93s] 
[   93s]   gmake[1]: *** [CMakeFiles/cmTC_18843.dir/build.make:78:
[   93s]   CMakeFiles/cmTC_18843.dir/printrpmver.c.o] Error 127
```

**Comment by DimStar77** [comment]
Reference: https://cmake.org/cmake/help/latest/policy/CMP0153.html

**Comment by bzeller** [comment]
This should actually only be executed as fallback ( and its debatable if we should have that fallback in the first place ), normally the cmake project files use pkg-config to look for gpgpme...

On what distribution release are you getting this error ?

**Comment by DimStar77** [comment]
openSUSE Tumbleweed - with the new cmake 3.28.0

**Comment by bzeller** [comment]
But why is pkg-config not used for you? Maybe we miss a build dependency

**Comment by DimStar77** [comment]
Debugged this a bit further with @bzeller 

The issue is in fact not find_exec, but the error comes from:

```
  SET( CMAKE_C_FLAGS     "${CMAKE_C_FLAGS} ${ZCHUNK_CFLAGS}" )
  SET( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${ZCHUNK_CFLAGS}" )
```

up to version 3.27, -I/usr/include was filtered out of CFLAGS, which resulted in the lucky situation of ZCHUNK_CFLAGS to have only one element. (if zck had defined a different include dir, the issue would have been there already)
