### ISSUE TITLE
17.12.0 -> 17.14.0,  Build failing with boost-1.70

### ISSUE THREAD

**Issue by jmrcpn** [openSUSE/libzypp#181]
Unable to have a success build using boost-1.70
;--------------------------------------------------------------------------------------------------------------
-- The C compiler identification is GNU 9.1.0
-- The CXX compiler identification is GNU 9.1.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building for SUSE
-- Libraries will be installed in /usr/lib
-- Header files will be installed in /usr/include
-- Config files will be installed in /etc
-- Performing Test CC_FORMAT_SECURITY
-- Performing Test CC_FORMAT_SECURITY - Failed
-- Performing Test CXX_FORMAT_SECURITY
-- Performing Test CXX_FORMAT_SECURITY - Failed
-- Looking for pipe2
-- Looking for pipe2 - found
-- Writing spec file...
-- I hate you rpm-lint...!!!
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- May use threads.
-- rpm found: includes in /usr/include, library in /usr/lib/librpm.so (suspect 4.x)
-- Found Boost 1.70.0 at /usr/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET REQUIRED COMPONENTS program_options;unit_test_framework;thread
-- Found boost_headers 1.70.0 at /usr/lib/cmake/boost_headers-1.70.0
-- Found boost_program_options 1.70.0 at /usr/lib/cmake/boost_program_options-1.70.0
--   libboost_program_options.a
-- Adding boost_program_options dependencies: headers
-- Found boost_unit_test_framework 1.70.0 at /usr/lib/cmake/boost_unit_test_framework-1.70.0
--   libboost_unit_test_framework.a
-- Adding boost_unit_test_framework dependencies: headers
-- Found boost_thread 1.70.0 at /usr/lib/cmake/boost_thread-1.70.0
--   libboost_thread.a
-- Adding boost_thread dependencies: headers
-- Boost  found.
-- Found Boost components:
   program_options;unit_test_framework;thread
-- boost found: includes in , library in 
-- Found Gettext: /usr/bin/msgmerge (found version "0.20.1") 
-- Found Gettext: 
-- Found CURL: /usr/lib/libcurl.so (found version "7.63.0") 
-- Found LibXml2: /usr/lib/libxml2.so (found version "2.9.9") 
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
-- Found LibSolv: /usr/lib/libsolv.so  
-- Found LibSolv_ext: /usr/lib/libsolvext.so  
-- Found LibSolv: /usr/include /usr/lib/libsolv.so;/usr/lib/libsolvext.so
-- Found gpgme-config at /usr/bin/gpgme-config
-- Found gpgme v1.13.1, checking for flavours...
--  Found flavour 'vanilla', checking whether it's usable...yes
--  Found flavour 'pthread', checking whether it's usable...yes
-- Usable gpgme flavours found:  vanilla pthread
-- Found libcrypto: /usr/lib/libcrypto.so
-- Found OpenSSL: /usr/lib/libssl.so
-- Looking for udev_enumerate_new
-- Looking for udev_enumerate_new - not found
-- Could NOT find Udev (missing: UDEV_LIBRARY UDEV_INCLUDE_DIR USABLE_UDEV) 
-- hal not found
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for one of the modules 'libproxy-1.0'
-- doxygen is not available. Can't build the documentation.
-- soname: 1712.0.0
-- version: 17.12.0
-- Writing pkg-config file...
-- FindZypp.cmake will be installed in /usr/share/cmake/Modules
-- zypp.conf will be installed in /etc/zypp
-- needreboot will be installed in /etc/zypp/
-- systemCheck will be installed in /etc/zypp
-- Configuring done
-- Generating done
;--------------------------------------------------------------------------------------
compilation start to fail....
;--------------------------------------------------------------------------------------
[ 88%] Built target zypp
[ 88%] Linking CXX executable zypp-pubkey
/usr/bin/ld: CMakeFiles/zypp-pubkey.dir/zypp-pubkey.cc.o: in function `boost::program_options::typed_value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>::xparse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const':
/usr/include/boost/program_options/detail/value_semantic.hpp:184: undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)'
/usr/bin/ld: CMakeFiles/zypp-pubkey.dir/zypp-pubkey.cc.o: in function `boost::program_options::error_with_option_name::~error_with_option_name()':
/usr/include/boost/program_options/errors.hpp:124: undefined reference to `vtable for boost::program_options::error_with_option_name'
/usr/bin/ld: CMakeFiles/zypp-pubkey.dir/zypp-pubkey.cc.o: in function `non-virtual thunk to boost::wrapexcept<boost::program_options::invalid_option_value>::~wrapexcept()':
zypp-pubkey.cc:(.text._ZN5boost10wrapexceptINS_15program_options20invalid_option_valueEED1Ev[_ZN5boost10wrapexceptINS_15program_options20invalid_option_valueEED1Ev]+0x4f): undefined reference to `vtable for boost::program_options::error_with_option_name
...........................
....
;--------------------------------------------------------------------------------------
same compilation context is working fine with boost-1.69

**Comment by mlandres** [comment]
Please do a `VERBOSE=1 make` so CMAKE shows the commandline and check whether `-lboost_program_options` is actually present.

Almost looks like the /usr/include/boost/program_options header files don't match the library. Do you have multiple boost versions installed? The `/usr/lib64/libboost_program_options.so` symlink points to `libboost_program_options.so.1.70.0` from package `libboost_program_options1_70_0-devel`?

**Comment by jmrcpn** [comment]
On 08/12/2019 04:27 AM, Michael Andres wrote:
> Please do a |VERBOSE=1 make| so CMAKE shows the commandline and check
> whether |-lboost_program_options| is actually present.
>
> Almost looks like the /usr/include/boost/program_options header files
> don't match the library. Do you have multiple boost versions installed?
> The |/usr/lib64/libboost_program_options.so| symlink points to
> |libboost_program_options.so.1.70.0| from package
> |libboost_program_options1_70_0-devel|?
>
> —
> You are receiving this because you authored the thread.
>
>
Problem seems to be within boost itself (new cmake).

Adding
-DBoost_NO_BOOST_CMAKE=ON
to cmake to build "resolv" the problem

Seems slackware see the problem too

see:
https://git.slackware.nl/current/plain/ChangeLog.rss

l/boost-1.70.0-x86_64-1.txz:  Upgraded.
#  Shared library .so-version bump.
#  Note: Boost now provides its own BoostConfig.cmake config file, and 
it may
#  not work with all existing code (here, calligra stumbled over it). At 
this
#  point it's not clear if the included cmake config files are buggy, or if
#  affected projects need to change something in order to use them, but 
there's
#  an easy workaround to use cmake's FindBoost.cmake (as was used 
previously).
#  Add this to the call to cmake from any affected project (if cmake 
fails with
#  an error: "No suitable build variant has been found."):
#  -DBoost_NO_BOOST_CMAKE=ON

-- 
seen "Linux from scratch" and looking for ISO files
www.osukiss.org

**Comment by mlandres** [comment]
Closing the issue due to the lack of activity. If indeed still persists, please reopen and report back.
