### ISSUE TITLE
libzypp fails to build with RPM 4.14 Alpha

### ISSUE THREAD

**Issue by ignatenkobrain** [openSUSE/libzypp#76]
```
/builddir/build/BUILD/libzypp-16.15.2/zypp/target/rpm/RpmHeader.cc:14:10: fatal error: rpm/ugid.h: No such file or directory
 #include <rpm/ugid.h>
          ^~~~~~~~~~~~
...
/builddir/build/BUILD/libzypp-16.15.2/zypp/target/rpm/BinHeader.cc:21:17: error: conflicting declaration 'typedef int32_t rpm_count_t'
 typedef int32_t rpm_count_t;
                 ^~~~~~~~~~~
In file included from /usr/include/rpm/rpmio.h:16:0,
                 from /usr/include/rpm/rpmlib.h:13,
                 from /builddir/build/BUILD/libzypp-16.15.2/zypp/target/rpm/librpm.h:25,
                 from /builddir/build/BUILD/libzypp-16.15.2/zypp/target/rpm/BinHeader.cc:12:
/usr/include/rpm/rpmtypes.h:29:18: note: previous declaration as 'typedef uint32_t rpm_count_t'
 typedef uint32_t rpm_count_t;
                  ^~~~~~~~~~~
/builddir/build/BUILD/libzypp-16.15.2/zypp/target/rpm/BinHeader.cc: In constructor 'zypp::target::rpm::HeaderEntryGetter::HeaderEntryGetter(headerToken_s* const&, rpmTag&)':
/builddir/build/BUILD/libzypp-16.15.2/zypp/target/rpm/BinHeader.cc:82:7: error: '::headerGetEntry' has not been declared
   { ::headerGetEntry( h_r, tag_r, hTYP_t(&_type), &_val, &_cnt ); }
       ^~~~~~~~~~~~~~
/builddir/build/BUILD/libzypp-16.15.2/zypp/target/rpm/BinHeader.cc:82:7: note: suggested alternative: 'headerIsEntry'
   { ::headerGetEntry( h_r, tag_r, hTYP_t(&_type), &_val, &_cnt ); }
       ^~~~~~~~~~~~~~
       headerIsEntry
/builddir/build/BUILD/libzypp-16.15.2/zypp/target/rpm/BinHeader.cc:82:35: error: 'hTYP_t' was not declared in this scope
   { ::headerGetEntry( h_r, tag_r, hTYP_t(&_type), &_val, &_cnt ); }
                                   ^~~~~~
```

**Comment by Conan-Kudo** [comment]
@mlandres: The current Git master builds with RPM 4.14: https://koji.fedoraproject.org/koji/buildinfo?buildID=956985

**Comment by mlandres** [comment]
Same as #76. The cmake module detected it as  RPM 4.4. that's why this ancient code got activated.  I removed this old stuff in master.
